version: '3.8'
services:
  web:
    build: ./web
    expose:
      - 5000
    environment:
      - PG_PASSWORD=student_password
      - PG_USER=student_user
      - PG_DATABASE=labo
      - PG_PORT=5432
      - PG_HOST=postgres
  postgres:
    image: 'postgres:13.0-alpine'
    environment:
      - POSTGRES_PASSWORD=student_password
      - POSTGRES_USER=student_user
      - POSTGRES_DB=labo
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
