name: TestFlow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: eslih.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build web/ -t eslih.azurecr.io/webapp:${{ github.sha }}
        docker build nginx/ -t eslih.azurecr.io/nginx:${{ github.sha }}
        docker push eslih.azurecr.io/webapp:${{ github.sha }}
        docker push eslih.azurecr.io/nginx:${{ github.sha }}          

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'eslih'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'eslih.azurecr.io/nginx:${{ github.sha }}'

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'eslih'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'eslih.azurecr.io/webapp:${{ github.sha }}'
