on: [push]

name: Linux_Container_Node_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: eslih.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build nginx/ -t eslih.azurecr.io/nginx:${{ github.sha }}
        docker push eslih.azurecr.io/nginx:${{ github.sha }}      
        docker build web/ -t eslih.azurecr.io/webapp:${{ github.sha }}
        docker push eslih.azurecr.io/webapp:${{ github.sha }}      
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'eslih3'
        configuration-file: docker-compose.yml
        images: |
          'eslih.azurecr.io/nginx:${{ github.sha }}'
          'eslih.azurecr.io/webapp:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout
